# Generated by Django 4.2.6 on 2023-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
